// @generated by protoc-gen-es v1.10.1
// @generated from file calculator.proto (package calculator, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message calculator.CalculateRequest
 */
export const CalculateRequest = /*@__PURE__*/ proto3.makeMessageType(
  "calculator.CalculateRequest",
  () => [
    { no: 1, name: "num1", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "num2", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "operator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message calculator.CalculateResponse
 */
export const CalculateResponse = /*@__PURE__*/ proto3.makeMessageType(
  "calculator.CalculateResponse",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

