// @generated by protoc-gen-connect-es v1.6.1
// @generated from file calculator.proto (package calculator, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CalculateRequest, CalculateResponse } from "./calculator_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service calculator.CalculatorService
 */
export const CalculatorService  = {
  typeName: "calculator.CalculatorService",
  methods: {
    /**
     * @generated from rpc calculator.CalculatorService.Calculate
     */
    calculate: {
      name: "Calculate",
      I: CalculateRequest,
      O: CalculateResponse,
      kind: MethodKind.Unary,
    },
  }
};

